### ISSUE TITLE
Android: Prevent crash if error joining experiment

### ISSUE THREAD

**Issue by BobEvans** [google/paco#1074]
In InformedConsentActivity, on Galaxy Note 4 devices, a particular experiment cannot be inserted into the experiments joined table. It causes a sql error that crashes the app.

Catch the error, log it, and present a message to the user that we could not join the experiment.

**Comment by BobEvans** [comment]
android.database.SQLException: Failed to insert row into content://com.google.android.apps.paco.ExperimentProvider/experiments
at com.pacoapp.paco.model.ExperimentProvider.insertExperiment(ExperimentProvider.java:252)
at com.pacoapp.paco.model.ExperimentProvider.insert(ExperimentProvider.java:198)
at android.content.ContentProvider$Transport.insert(ContentProvider.java:236)
at android.content.ContentResolver.insert(ContentResolver.java:1205)
at com.pacoapp.paco.model.ExperimentProviderUtil.insertFullJoinedExperiment(ExperimentProviderUtil.java:161)
at com.pacoapp.paco.ui.InformedConsentActivity.joinExperiment(InformedConsentActivity.java:291)
at com.pacoapp.paco.ui.InformedConsentActivity.saveDownloadedExperimentBeforeScheduling(InformedConsentActivity.java:196)
at com.pacoapp.paco.ui.InformedConsentActivity.requestFullExperimentForJoining(InformedConsentActivity.java:168)
at com.pacoapp.paco.ui.InformedConsentActivity.access$100(InformedConsentActivity.java:69)
at com.pacoapp.paco.ui.InformedConsentActivity$1.onClick(InformedConsentActivity.java:133)
at android.view.View.performClick(View.java:4785)
at android.widget.CompoundButton.performClick(CompoundButton.java:120)
at android.view.View$PerformClick.run(View.java:19884)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
